### ISSUE TITLE
Slow model loads

### ISSUE THREAD

**Issue by bernii** [patienceai/stable-diffusion-automatic1111-banana#1]
Hi!

I'm experiencing slow model loads (>120s) when running this template on `bannna.dev` - have you seen the same? Any chance to lower the load time?

**Comment by patienceai** [comment]
Hi,
Cold starts for this template are around 15-20s normally, but banana has been experiencing some service and capacity issues this week, leading to longer start times. Hopefully the situation will improve soon.
